export const ipl = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/ipl.jpg?alt=media';
export const first ='https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/first.png?alt=media';
export const second ='https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/second.png?alt=media';
export const third ='https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/third.png?alt=media';
export const profile ='https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/profile-section.jpg?alt=media';
export const register ='https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/register.jpg?alt=media';
export const stadium ='https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/stadium.jpg?alt=media';
export const userbadge = 'https://firebasestorage.googleapis.com/v0/b/sportsgeek-74e1e.appspot.com/o/69bba4a0-c114-4379-9854-e4381a3130bc.png?alt=media';
export const allteams = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/allteams.jpg?alt=media';
export const chennaiWin = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/chennaiWon2021.jpg?alt=media';
export const trophy = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/trophy.jpg?alt=media';
export const teamFlags = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/team_flags.jpg?alt=media';
export const otherUser = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/otherUser.jpg?alt=media';
export const csk = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/csk.gif?alt=media';
export const mi = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/mi.gif?alt=media';
export const gt = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/gt.gif?alt=media';
export const lsg = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/lgt.gif?alt=media';
export const kkr = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/kkr.gif?alt=media';
export const rcb = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/rcb.gif?alt=media';
export const rr = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/rr.gif?alt=media';
export const pbks = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/pbks.gif?alt=media';
export const srh = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/srh.gif?alt=media';
export const dc = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/dc.gif?alt=media';
export const place_bet_music = 'https://firebasestorage.googleapis.com/v0/b/react-128c5.appspot.com/o/place_contest.mp3?alt=media';
